### ISSUE TITLE
Error while compiling permissioning smart contracts with new compiler version (0.8.7)

### ISSUE THREAD

**Issue by trinayanbhatt** [ConsenSys/quorum-dev-quickstart#241]
The permissioning smart contracts available under this repository to implement enhanced permissioning is utilizing older smart contract compiler (^0.5.3). 

So, if we try to update the solidity contracts to compile with newer version(v0.8.7) then it throws compilation error on VoterManager smart contract as the OrgVoterDetails struct is having mappings inside it which is not supported with the newer solidity compiler versions.

Can someone help with the upgraded smart contracts or some other functionality to implement enhanced permissioning in our quorum based network architecture?

**Comment by joshuafernandes** [comment]
@antonydenyer is this something you can look at mate?

**Comment by antonydenyer** [comment]
This is actually a copy from

https://github.com/ConsenSys/quorum/blob/master/permission/v2/contract/VoterManager.sol

Realistically we're not going to get the time to update them any time soon. My preference would be to have https://github.com/ConsenSys/quorum/issues/1102 implemented so that people can more easily implement their own solutions. If you get the chance a PR would be greatly appreciated.
